import { Router, type Router as ExpressRouter } from "express";
import { requireAuth } from "../middlewares/authMiddleware.js";
import * as handlers from "../controllers/payrollEmailController.js";
const router: ExpressRouter = Router();
router.post("/internal/jobs/:id", handlers.processPayrollJobHandler);
router.post("/internal/recover", handlers.recoverPayrollJobsHandler);
router.use(requireAuth);
router.get("/catalog", handlers.fetchPayrollCatalogHandler);
router.put("/templates/:id", handlers.updatePayrollTemplateHandler);
router.put("/signatures/:id", handlers.updatePayrollSignatureHandler);
router.get("/drafts", handlers.fetchPayrollDraftsHandler);
router.put("/drafts/:id", handlers.updatePayrollDraftHandler);
router.get("/drafts/:id", handlers.fetchPayrollDraftHandler);
router.put("/drafts/:id/recipients/:person", handlers.updatePayrollRecipientHandler);
router.get("/drafts/:id/recipients", handlers.fetchPayrollRecipientsHandler);
router.post("/drafts/:id/preview", handlers.previewPayrollEmailHandler);
router.post("/drafts/:id/test", handlers.sendPayrollTestHandler);
router.post("/drafts/:id/export", handlers.exportPayrollEmailHandler);
router.post("/jobs", handlers.createPayrollJobHandler);
router.get("/jobs/:id", handlers.fetchPayrollJobHandler);
router.post("/jobs/:id/retry", handlers.retryPayrollItemsHandler);
router.get("/history", handlers.fetchPayrollHistoryHandler);
router.post("/history/:id/export", handlers.exportPayrollHistoryHandler);
router.delete("/templates/:id", handlers.removePayrollTemplateHandler);
router.delete("/signatures/:id", handlers.removePayrollSignatureHandler);
export default router;
